name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  make-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run make check
      run: make check

  make-check-valgrind:
    runs-on: ubuntu-latest

    steps:
    - name: Install Valgrind
      run: |
        sudo apt install valgrind -y
        echo "Valgrind installed"

    - uses: actions/checkout@v3
    - name: Run make check-valgrind
      run: make check-valgrind

  make-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Install cppcheck
        run: |
          sudo apt install cppcheck -y
          echo "cppcheck installed"

      - uses: actions/checkout@v3
      - name: Run make lint
        run: make lint
